# Generated by Django 3.1.7 on 2021-03-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='link',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
